name: fairy_flutter_utils
description: Flutter package util工具类,包含日期时间,数字,定时器,字符串,集合,货币,正则表达式,集合,签名等工具的封装.
version: 0.0.1-dev
#author: liucj123558@gmail.com
homepage: https://github.com/FairyHeart/fairy_flutter_package_utils

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # EncryptUtil
  # https://github.com/a14n/dart-decimal
  decimal: ">=1.0.0 <3.0.0"

  # EncryptUtil
  # https://github.com/dart-lang/crypto
  crypto: ">=3.0.0 <5.0.0"

  # NumUtil
  # https://github.com/dart-lang/convert
  convert: ">=3.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
